# Generated by Django 3.0.2 on 2020-01-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("standard", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=50)),
            ],
            options={"ordering": ["-standard", "name"],},
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_year", models.PositiveIntegerField()),
                ("to_year", models.PositiveIntegerField()),
            ],
            options={"ordering": ["-from_year", "to_year"],},
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subjects",
                        to="main_app.Group",
                    ),
                ),
            ],
            options={"ordering": ["group", "name"],},
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "subjects",
                    models.ManyToManyField(
                        related_name="batches", to="main_app.Subject"
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="main_app.Year",
                    ),
                ),
            ],
            options={"verbose_name_plural": "batches", "ordering": ["name"],},
        ),
    ]
