# Generated by Django 3.0.2 on 2020-01-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200116_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['name'], 'verbose_name_plural': 'batches'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['group', 'name']},
        ),
    ]
